[package]
name = "qubit-task"
version = "0.4.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-task"
description = "Task-oriented services built on top of qubit-executor and qubit-thread-pool"
homepage = "https://github.com/qubit-ltd/rs-task"
documentation = "https://docs.rs/qubit-task"
readme = "README.md"
keywords = ["task", "concurrent", "executor", "service"]
categories = ["concurrency", "asynchronous"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/RUST_CODING_STYLE.md",
    "/RUST_CODING_STYLE.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_task"
doctest = true
test = false

[dependencies]
qubit-executor = { version = "0.7" }
qubit-thread-pool = { version = "0.9" }
qubit-function = "0.15"
thiserror = "2.0"
