[package]
name = "qubit-task"
version = "0.6.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-task"
description = "Resource-aware asynchronous task execution service"
homepage = "https://github.com/qubit-ltd/rs-task"
documentation = "https://docs.rs/qubit-task"
readme = "README.md"
keywords = ["task", "concurrent", "executor", "service"]
categories = ["concurrency", "asynchronous"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/doc/**",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_task"
doctest = true
test = true

[dependencies]
futures = "^0.3"
fs2 = { version = "^0.4", optional = true }
parking_lot = "^0.12"
qubit-event-bus = { version = "0.14", path = "../rs-event-bus", optional = true }
qubit-id = { version = "0.6", features = ["uuid"] }
qubit-spi = "0.13"
rusqlite = { version = "^0.32", features = ["bundled"], optional = true }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tokio = { version = "^1.53", features = ["rt-multi-thread", "sync", "time"] }
thiserror = "^2.0"
uuid = { version = "^1.0", features = ["v4", "serde"] }

[features]
default = []
inventory = ["qubit-spi/inventory"]
sqlite = ["dep:rusqlite", "dep:fs2"]
event-bus = ["dep:qubit-event-bus"]

[dev-dependencies]
tokio = { version = "^1.53", features = ["macros", "rt-multi-thread", "time"] }
