[package]
name = "qubit-task"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-task"
description = "Task-oriented services built on top of qubit-executor and qubit-thread-pool"
homepage = "https://github.com/qubit-ltd/rs-task"
documentation = "https://docs.rs/qubit-task"
readme = "README.md"
keywords = ["task", "concurrent", "executor", "service"]
categories = ["concurrency", "asynchronous"]
exclude = [
    "align-ci.sh",
    "ci-check.sh",
    "coverage.sh",
    "style-check.sh",
    "update-submodule.sh",
    ".github/*",
    ".llvm-cov.toml",
    ".cargo-audit.toml.example",
]

[lib]
name = "qubit_task"
doctest = true
test = false

[dependencies]
qubit-executor = { version = "0.3" }
qubit-thread-pool = { version = "0.5" }
qubit-function = "0.13"
thiserror = "2.0"

[patch.crates-io]
qubit-executor = { version = "0.3.1", path = "../rs-executor" }
