use qubit_id::Id;
use serde::Deserialize;
use serde::Serialize;

/// Stable unsigned task identity generated by the configured ID generator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TaskId(Id);

impl TaskId {
    /// Wraps a generated identifier.
    pub const fn from_id(id: Id) -> Self {
        Self(id)
    }

    /// Returns the underlying numeric identifier.
    pub const fn into_id(self) -> Id {
        self.0
    }

    /// Returns the fixed-width decimal key used by ordered text stores.
    pub fn to_padded_decimal(self) -> String {
        format!("{:020}", self.0.value())
    }
}

impl std::fmt::Display for TaskId {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(formatter)
    }
}
