[package]
name = "qubit-task-all-features-consumer"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
sqlite = ["qubit-task/sqlite"]
inventory = ["qubit-task/inventory"]
event-bus = ["qubit-task/event-bus"]

[dependencies]
qubit-task = { path = "../../..", default-features = false }
qubit-id = { path = "../../../../rs-id", version = "0.6" }
